-- =========================================================
-- 角色管理 Oracle 数据库设计脚本
-- 适用范围：角色管理、菜单树、角色菜单授权
-- 兼容建议：Oracle 11g+（使用 SEQUENCE + TRIGGER）
-- =========================================================

-- =========================
-- 1. 角色表
-- =========================
CREATE TABLE SYS_ROLE (
  ROLE_ID       NUMBER(19)      NOT NULL,
  ROLE_NAME     VARCHAR2(60)    NOT NULL,
  ROLE_KEY      VARCHAR2(100)   NOT NULL,
  ROLE_SORT     NUMBER(10)      DEFAULT 0 NOT NULL,
  STATUS        NUMBER(1)       DEFAULT 1 NOT NULL,
  REMARK        VARCHAR2(500),
  CREATE_BY     VARCHAR2(64),
  CREATE_TIME   DATE            DEFAULT SYSDATE NOT NULL,
  UPDATE_BY     VARCHAR2(64),
  UPDATE_TIME   DATE,
  CONSTRAINT PK_SYS_ROLE PRIMARY KEY (ROLE_ID),
  CONSTRAINT UK_SYS_ROLE_KEY UNIQUE (ROLE_KEY),
  CONSTRAINT CK_SYS_ROLE_STATUS CHECK (STATUS IN (0, 1))
);

COMMENT ON TABLE SYS_ROLE IS '角色表';
COMMENT ON COLUMN SYS_ROLE.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN SYS_ROLE.ROLE_KEY IS '权限字符，建议唯一';
COMMENT ON COLUMN SYS_ROLE.ROLE_SORT IS '显示排序';
COMMENT ON COLUMN SYS_ROLE.STATUS IS '状态：1正常，0停用';
COMMENT ON COLUMN SYS_ROLE.REMARK IS '备注';
COMMENT ON COLUMN SYS_ROLE.CREATE_BY IS '创建人';
COMMENT ON COLUMN SYS_ROLE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_ROLE.UPDATE_BY IS '更新人';
COMMENT ON COLUMN SYS_ROLE.UPDATE_TIME IS '更新时间';

CREATE SEQUENCE SEQ_SYS_ROLE START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_SYS_ROLE_BI
BEFORE INSERT ON SYS_ROLE
FOR EACH ROW
BEGIN
  IF :NEW.ROLE_ID IS NULL THEN
    SELECT SEQ_SYS_ROLE.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
  END IF;

  IF :NEW.CREATE_TIME IS NULL THEN
    :NEW.CREATE_TIME := SYSDATE;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SYS_ROLE_BU
BEFORE UPDATE ON SYS_ROLE
FOR EACH ROW
BEGIN
  :NEW.UPDATE_TIME := SYSDATE;
END;
/

CREATE INDEX IDX_SYS_ROLE_NAME   ON SYS_ROLE (ROLE_NAME);
CREATE INDEX IDX_SYS_ROLE_STATUS ON SYS_ROLE (STATUS);
CREATE INDEX IDX_SYS_ROLE_SORT   ON SYS_ROLE (ROLE_SORT);

-- =========================
-- 2. 菜单表
-- =========================
CREATE TABLE SYS_MENU (
  MENU_ID       NUMBER(19)      NOT NULL,
  PARENT_ID     NUMBER(19)      DEFAULT 0 NOT NULL,
  MENU_NAME     VARCHAR2(100)   NOT NULL,
  MENU_TYPE     CHAR(1)         DEFAULT 'M' NOT NULL,
  PATH          VARCHAR2(200),
  COMPONENT     VARCHAR2(200),
  PERMS         VARCHAR2(200),
  ICON          VARCHAR2(100),
  ORDER_NUM     NUMBER(10)      DEFAULT 0 NOT NULL,
  STATUS        NUMBER(1)       DEFAULT 1 NOT NULL,
  REMARK        VARCHAR2(500),
  CREATE_BY     VARCHAR2(64),
  CREATE_TIME   DATE            DEFAULT SYSDATE NOT NULL,
  UPDATE_BY     VARCHAR2(64),
  UPDATE_TIME   DATE,
  CONSTRAINT PK_SYS_MENU PRIMARY KEY (MENU_ID),
  CONSTRAINT CK_SYS_MENU_STATUS CHECK (STATUS IN (0, 1)),
  CONSTRAINT CK_SYS_MENU_TYPE CHECK (MENU_TYPE IN ('M', 'C', 'B'))
);

COMMENT ON TABLE SYS_MENU IS '菜单表';
COMMENT ON COLUMN SYS_MENU.MENU_ID IS '菜单ID';
COMMENT ON COLUMN SYS_MENU.PARENT_ID IS '父菜单ID，顶级为0';
COMMENT ON COLUMN SYS_MENU.MENU_NAME IS '菜单名称';
COMMENT ON COLUMN SYS_MENU.MENU_TYPE IS '菜单类型：M目录，C菜单，B按钮';
COMMENT ON COLUMN SYS_MENU.PATH IS '路由路径';
COMMENT ON COLUMN SYS_MENU.COMPONENT IS '前端组件路径';
COMMENT ON COLUMN SYS_MENU.PERMS IS '权限标识';
COMMENT ON COLUMN SYS_MENU.ICON IS '图标';
COMMENT ON COLUMN SYS_MENU.ORDER_NUM IS '显示排序';
COMMENT ON COLUMN SYS_MENU.STATUS IS '状态：1正常，0停用';
COMMENT ON COLUMN SYS_MENU.REMARK IS '备注';

CREATE SEQUENCE SEQ_SYS_MENU START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_SYS_MENU_BI
BEFORE INSERT ON SYS_MENU
FOR EACH ROW
BEGIN
  IF :NEW.MENU_ID IS NULL THEN
    SELECT SEQ_SYS_MENU.NEXTVAL INTO :NEW.MENU_ID FROM DUAL;
  END IF;

  IF :NEW.CREATE_TIME IS NULL THEN
    :NEW.CREATE_TIME := SYSDATE;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SYS_MENU_BU
BEFORE UPDATE ON SYS_MENU
FOR EACH ROW
BEGIN
  :NEW.UPDATE_TIME := SYSDATE;
END;
/

CREATE INDEX IDX_SYS_MENU_PARENT ON SYS_MENU (PARENT_ID);
CREATE INDEX IDX_SYS_MENU_STATUS ON SYS_MENU (STATUS);
CREATE INDEX IDX_SYS_MENU_ORDER  ON SYS_MENU (ORDER_NUM);
CREATE INDEX IDX_SYS_MENU_PERMS  ON SYS_MENU (PERMS);

-- =========================
-- 3. 角色菜单关联表
-- =========================
CREATE TABLE SYS_ROLE_MENU (
  ROLE_ID       NUMBER(19)      NOT NULL,
  MENU_ID       NUMBER(19)      NOT NULL,
  CREATE_TIME   DATE            DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SYS_ROLE_MENU PRIMARY KEY (ROLE_ID, MENU_ID),
  CONSTRAINT FK_SYS_ROLE_MENU_ROLE FOREIGN KEY (ROLE_ID)
    REFERENCES SYS_ROLE (ROLE_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SYS_ROLE_MENU_MENU FOREIGN KEY (MENU_ID)
    REFERENCES SYS_MENU (MENU_ID) ON DELETE CASCADE
);

COMMENT ON TABLE SYS_ROLE_MENU IS '角色菜单关联表';
COMMENT ON COLUMN SYS_ROLE_MENU.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE_MENU.MENU_ID IS '菜单ID';
COMMENT ON COLUMN SYS_ROLE_MENU.CREATE_TIME IS '授权时间';

CREATE INDEX IDX_SYS_ROLE_MENU_MENU ON SYS_ROLE_MENU (MENU_ID);

-- =========================
-- 4. 可选扩展：用户角色关联表
-- 如果后端删除角色前需要校验“是否绑定用户”，建议加上
-- =========================
CREATE TABLE SYS_USER_ROLE (
  USER_ID       NUMBER(19)      NOT NULL,
  ROLE_ID       NUMBER(19)      NOT NULL,
  CREATE_TIME   DATE            DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SYS_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_SYS_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID)
    REFERENCES SYS_ROLE (ROLE_ID) ON DELETE CASCADE
);

COMMENT ON TABLE SYS_USER_ROLE IS '用户角色关联表';
COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS '角色ID';

CREATE INDEX IDX_SYS_USER_ROLE_ROLE ON SYS_USER_ROLE (ROLE_ID);

-- =========================
-- 5. 初始化菜单数据示例
-- =========================
INSERT INTO SYS_MENU (MENU_ID, PARENT_ID, MENU_NAME, MENU_TYPE, PATH, COMPONENT, PERMS, ICON, ORDER_NUM, STATUS, REMARK)
VALUES (1, 0, '系统管理', 'M', '/system', NULL, NULL, 'setting', 1, 1, '系统管理根目录');

INSERT INTO SYS_MENU (MENU_ID, PARENT_ID, MENU_NAME, MENU_TYPE, PATH, COMPONENT, PERMS, ICON, ORDER_NUM, STATUS, REMARK)
VALUES (11, 1, '角色管理', 'C', '/system/role', '@/views/system/role/RoleView.vue', 'system:role:list', 'user-filled', 1, 1, '角色管理页面');

INSERT INTO SYS_MENU (MENU_ID, PARENT_ID, MENU_NAME, MENU_TYPE, PATH, COMPONENT, PERMS, ICON, ORDER_NUM, STATUS, REMARK)
VALUES (111, 11, '角色新增', 'B', NULL, NULL, 'system:role:add', NULL, 1, 1, '新增角色按钮');

INSERT INTO SYS_MENU (MENU_ID, PARENT_ID, MENU_NAME, MENU_TYPE, PATH, COMPONENT, PERMS, ICON, ORDER_NUM, STATUS, REMARK)
VALUES (112, 11, '角色编辑', 'B', NULL, NULL, 'system:role:edit', NULL, 2, 1, '编辑角色按钮');

INSERT INTO SYS_MENU (MENU_ID, PARENT_ID, MENU_NAME, MENU_TYPE, PATH, COMPONENT, PERMS, ICON, ORDER_NUM, STATUS, REMARK)
VALUES (113, 11, '角色删除', 'B', NULL, NULL, 'system:role:remove', NULL, 3, 1, '删除角色按钮');

INSERT INTO SYS_MENU (MENU_ID, PARENT_ID, MENU_NAME, MENU_TYPE, PATH, COMPONENT, PERMS, ICON, ORDER_NUM, STATUS, REMARK)
VALUES (114, 11, '角色授权', 'B', NULL, NULL, 'system:role:grant', NULL, 4, 1, '角色授权按钮');

-- =========================
-- 6. 初始化角色数据示例
-- =========================
INSERT INTO SYS_ROLE (ROLE_ID, ROLE_NAME, ROLE_KEY, ROLE_SORT, STATUS, REMARK, CREATE_BY)
VALUES (1, '系统管理员', 'system:admin', 1, 1, '默认管理员角色', 'system');

INSERT INTO SYS_ROLE (ROLE_ID, ROLE_NAME, ROLE_KEY, ROLE_SORT, STATUS, REMARK, CREATE_BY)
VALUES (2, '普通运营', 'system:operator', 2, 1, '普通运营角色', 'system');

-- 管理员拥有全部角色管理菜单权限
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID) VALUES (1, 1);
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID) VALUES (1, 11);
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID) VALUES (1, 111);
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID) VALUES (1, 112);
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID) VALUES (1, 113);
INSERT INTO SYS_ROLE_MENU (ROLE_ID, MENU_ID) VALUES (1, 114);

COMMIT;
